version: "3"
services:
  langchain-app:
    build: .
    volumes:
      - ./:/app
      - ./source_code:/code_repo # Mount your source code repository here
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    ports:
      - "8000:8000"
    depends_on:
      - chroma

  chroma:
    image: chromadb/chroma:latest
    volumes:
      - chroma-data:/chroma/chroma
    ports:
      - "8001:8000"

volumes:
  chroma-data:
